import { ACTIONS, type Action } from "./actions.js";
import { ROLES, type Role } from "./roles.js";

const ALLOWED: Record<Action, readonly Role[]> = {
  [ACTIONS.PARTNER_CREATE]: [ROLES.SUPER_ADMIN],
  [ACTIONS.CUSTOMER_GROUP_CREATE]: [ROLES.SUPER_ADMIN, ROLES.PARTNER_ADMIN],
  [ACTIONS.MEMBER_INVITE_PARTNER_ADMIN]: [ROLES.SUPER_ADMIN],
  [ACTIONS.MEMBER_INVITE_PARTNER_USER]: [ROLES.SUPER_ADMIN, ROLES.PARTNER_ADMIN],
  [ACTIONS.MEMBER_INVITE_CUSTOMER_ADMIN]: [ROLES.SUPER_ADMIN, ROLES.PARTNER_ADMIN],
  [ACTIONS.MEMBER_INVITE_CUSTOMER_USER]: [ROLES.SUPER_ADMIN, ROLES.PARTNER_ADMIN, ROLES.CUSTOMER_ADMIN],
  [ACTIONS.RESOURCE_MANAGE]: [ROLES.SUPER_ADMIN, ROLES.PARTNER_ADMIN, ROLES.CUSTOMER_ADMIN],
  [ACTIONS.RESOURCE_READ]: [
    ROLES.SUPER_ADMIN,
    ROLES.PARTNER_ADMIN,
    ROLES.PARTNER_USER,
    ROLES.CUSTOMER_ADMIN,
    ROLES.CUSTOMER_USER
  ]
};

export function roleAllowsAction(role: Role, action: Action): boolean {
  return ALLOWED[action].includes(role);
}

export function allowedRolesFor(action: Action): readonly Role[] {
  return ALLOWED[action];
}
